# Workflowの名前。任意に設定可能
name: EC2 auto deploy

# アクションが実行されるタイミングを設定。今回はdevelopブランチにpushされた時。
on:
 push:
   branches:
     - develop
 
#実行される処理
jobs:
 build:
   # 実行環境の指定
   runs-on: ubuntu-latest
   steps:
     - shell: bash
       env:
         USER_NAME: ${{ secrets.USER_NAME }}
       run: |
         echo "$USER_NAME"   
    
