# Workflowの名前。任意に設定可能
name: EC2 auto deploy
# アクションが実行されるタイミングを設定。今回はdevelopブランチにpushされた時。
on:
 push:
   branches:
     - develop
 
#実行される処理
jobs:
 build:
   # 実行環境の指定
   runs-on: ubuntu-latest
   environment: sg-ames-project
   env:
    USER_NAME: ${{ secrets.USER_NAME }}
    BACKEND_HOST_NAME: ${{ secrets.BACKEND_HOST_NAME }}
    FRONTEND_HOST_NAME: ${{ secrets.FRONTEND_HOST_NAME }}
    PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
   steps:
     # デプロイする
     - name: Deploy
       run: |
         # SSH接続して、git pullする
         echo "$PRIVATE_KEY" > private_key
         chmod 600 private_key
         ssh -oStrictHostKeyChecking=no -i private_key $USER_NAME@$BACKEND_HOST_NAME "cd /var/www/UmaLifeGo/backend/ && git pull"
         ssh -oStrictHostKeyChecking=no -i private_key $USER_NAME@$FRONTEND_HOST_NAME "systemctl stop nginx && cd /var/www/UmaLifeGo/frontend/ && git pull && npm run build && cd /usr/share/nginx/html && yes | cp -rf /var/www/UmaLifeGo/frontend/dist/* ./ && systemctl start nginx"
         rm private_key
