# Workflowの名前。任意に設定可能
name: EC2 auto deploy
# アクションが実行されるタイミングを設定。今回はdevelopブランチにpushされた時。
on:
 push:
   branches:
     - develop
 
#実行される処理
jobs:
 build:
   # 実行環境の指定
   runs-on: ubuntu-latest
   env:
    USER_NAME: ${{ secrets.USER_NAME }}
   steps:
     # デプロイする
     - name: Deploy
       run: |
         # SSH接続して、git pullする
         echo "$USER_NAME"
         echo "${{ secrets.PRIVATE_KEY }}" > private_key
         echo "hello sin" > hello
         chmod 700 private_key
         cat private_key
         cat hello
         rm private_key
