# Workflowの名前。任意に設定可能
name: EC2 auto deploy

# アクションが実行されるタイミングを設定。今回はdevelopブランチにpushされた時。
on:
 push:
   branches:
     - develop
 
#実行される処理
jobs:
 build:
   # 実行環境の指定
   runs-on: ubuntu-latest
   steps:

     # デプロイする
     - name: Deploy
       run: |
         # SSH接続して、git pullする
         echo "${{ secrets.PRIVATE_KEY }}" > private_key
         chmod 700 private_key
         ssh -oStrictHostKeyChecking=no ${{ secrets.USER_NAME }}@${{ secrets.BACKEND_HOST_NAME }} -i private_key "cd /var/www/UmaLifeGo/backend/ && git pull && npm run start"
         ssh -oStrictHostKeyChecking=no ${{ secrets.USER_NAME }}@${{ secrets.FRONTEND_HOST_NAME }} -i private_key "systemctl stop nginx && cd /var/www/UmaLifeGo/frontend/ && git pull && npm run build && cd /usr/share/nginx/html && yes | cp -rf /var/www/UmaLifeGo/frontend/dist/* ./ && systemctl start nginx"
         rm private_key
         
